# Arreglos
## Matrices
Una matriz es una forma de ordenar un sistema de ecuaciones, para que tenga un uso más sencillo.

\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1m} \\
a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nm}
\end{bmatrix}


In [2]:
A= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print (A)
type (A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [4]:
#Vamos a crear otra lista de listas.
B=[[21, 34, 40], [71, 17, 77], [73, 81, 28]]
A+B #Concatenar las listas.
print (A+B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [73, 81, 28]]


In [5]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
A[0][0]
[1, 2, 3]
#A [0,0]

[1, 2, 3]

## Vectores y Listas


In [8]:
L= A[0]
M= B[0]
print (L, M)


[1, 2, 3] [21, 34, 40]


In [9]:
a= L[0]
b= M[0]
a+b

22

In [10]:
a==1

True

### Suma de Vectores


In [11]:
len (L)==len (M)

True

In [12]:
suma=[L[0]+ M[0], L[1]+ M[1], L[2]+ M[2]]

In [14]:
suma=[L[i]+M[i] for i in range(3)]

### Creación de Funciones Globales
La función para crear funciones se llama `def` que se cierra con un debug (print) ó (return)

In [15]:
 def Hola():
  print("Hola, me llamo Cesar")

In [16]:
Hola()

Hola, me llamo Cesar


In [24]:
def Saludar(s, n):
  print (f"Hola, me llamo {s} y tengo {n} años")

In [25]:
Saludar("Cesar", 18)

Hola, me llamo Cesar y tengo 18 años


In [27]:
def par():
  for x in range (10):
    if x%2==0:
      print(f"{x} es par")
    else:
        print(f"{x} es impar")

In [28]:
par()


0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [31]:
def suma_vectorial(L,M):
  x=[L[i]+M[i] for i in range(len(L))]
  print (M,L)

### Modulos y Librerias

In [32]:
import math
from math import sqrt, pi

In [33]:
sqrt(25)

5.0

In [35]:
pi

3.141592653589793

## El módulo NumPy
La función `array`

In [36]:
import numpy as np
L_vector = np.array(L)
M_vector = np.array(M)
L_vector + M_vector

array([22, 36, 43])

In [45]:
C=[9,2,2,2,3,4,6,5,23]
A=[0,1,1,1,2,1,16,1,6]
C_matriz = np.array (C). reshape (3,3)
A_matriz= np.array (A). reshape (3,3)
print (C_matriz)
print (A_matriz)

[[ 9  2  2]
 [ 2  3  4]
 [ 6  5 23]]
[[ 0  1  1]
 [ 1  2  1]
 [16  1  6]]


In [46]:
C_matriz @ A_matriz

array([[ 34,  15,  23],
       [ 67,  12,  29],
       [373,  39, 149]])

In [47]:
A_matriz @ C_matriz

array([[  8,   8,  27],
       [ 19,  13,  33],
       [182,  65, 174]])